image: node:latest
stages:
  - test

variables:
  PROJECT_NAME: algorithmia
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  RUNNING_ON_BUILD_SERVER: "true"

test_async:
  stage: test
  script:
  - tsc
  - if [ -z $ALGORITHMIA_DEFAULT_API_KEY ]; then echo "Algorithmia API key not defined"; exit 1; fi
  - npm test
